# Use Tomcat base image
FROM tomcat:9-jdk11-openjdk

# Set the working directory
WORKDIR /usr/local/tomcat/webapps

# Copy the JAR file into the container (from the target folder)
COPY target/MyJavaProject.jar /usr/local/tomcat/webapps/ROOT.jar

# Expose the port that Tomcat runs on
EXPOSE 8080

# Start Tomcat server
CMD ["catalina.sh", "run"]
